/**
 * Build-time skill bundler. Inlines every `agent-skills/<name>/SKILL.md` and its
 * `references/` files into a generated TypeScript registry that the Convex
 * deployment can import (Convex functions cannot read the filesystem).
 *
 * Run via `npm run skills:bundle` (also wired as predev / prebuild / preconvex).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { readSkillsFromDisk } from "../src/lib/skills/fs-source";

const OUT = join("src", "lib", "skills", "registry.generated.ts");

function main() {
  const { version, skills } = readSkillsFromDisk("agent-skills");

  const entries = skills
    .map((s) => {
      return `  ${JSON.stringify(s.name)}: {
    name: ${JSON.stringify(s.name)},
    description: ${JSON.stringify(s.description)},
    directory: ${JSON.stringify(s.directory)},
    content: ${JSON.stringify(s.content)},
  },`;
    })
    .join("\n");

  const banner =
    "// AUTO-GENERATED by scripts/bundle-skills.ts. Do not edit by hand.\n" +
    "// Regenerate with `npm run skills:bundle`.\n";

  const body = `${banner}
import type { Skill } from "./types";

export const SKILLS_VERSION = ${JSON.stringify(version)};

export const SKILL_REGISTRY: Record<string, Skill> = {
${entries}
};
`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body, "utf8");
  // eslint-disable-next-line no-console
  console.log(
    `Bundled ${skills.length} skill(s) → ${OUT} (version ${version}): ${skills
      .map((s) => s.name)
      .join(", ")}`,
  );
}

main();
