#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=20

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 is required but was not found"
    exit 1
  fi
}

set_shared_variable() {
  local key="$1" value="$2" sealed="${3:-true}"
  KEY="$key" VALUE="$value" SEALED="$sealed" node <<'NODE' |
const patch = {
  sharedVariables: {
    [process.env.KEY]: {
      value: process.env.VALUE,
      isSealed: process.env.SEALED === "true",
    },
  },
};
process.stdout.write(JSON.stringify(patch));
NODE
    railway environment edit --json >/dev/null
  printf '  %s✓ set%s Railway shared variable %s\n' "$GREEN" "$RESET" "$key"
}

shared_variable_exists() {
  local key="$1"
  KEY="$key" railway environment config --json | KEY="$key" node -e '
    let input = "";
    process.stdin.on("data", (chunk) => (input += chunk));
    process.stdin.on("end", () => {
      const target = process.env.KEY;
      const visit = (value) => {
        if (!value || typeof value !== "object") return false;
        if (value.sharedVariables &&
            Object.prototype.hasOwnProperty.call(value.sharedVariables, target)) return true;
        return Object.values(value).some(visit);
      };
      try { process.exit(visit(JSON.parse(input)) ? 0 : 1); }
      catch { process.exit(1); }
    });
  '
}

json_railway_domain() {
  node -e '
    let input = "";
    process.stdin.on("data", (chunk) => (input += chunk));
    process.stdin.on("end", () => {
      const visit = (value) => {
        if (typeof value === "string" && value.endsWith(".railway.app")) return value;
        if (Array.isArray(value)) {
          for (const item of value) {
            const found = visit(item);
            if (found) return found;
          }
        } else if (value && typeof value === "object") {
          for (const item of Object.values(value)) {
            const found = visit(item);
            if (found) return found;
          }
        }
      };
      try {
        const domain = visit(JSON.parse(input));
        if (domain) process.stdout.write(domain);
      } catch {}
    });
  '
}

latest_deployment_status() {
  node -e '
    let input = "";
    process.stdin.on("data", (chunk) => (input += chunk));
    process.stdin.on("end", () => {
      try {
        const value = JSON.parse(input);
        const deployments = Array.isArray(value)
          ? value
          : value.deployments ?? value.items ?? value.edges?.map((edge) => edge.node) ?? [];
        process.stdout.write(deployments[0]?.status ?? "UNKNOWN");
      } catch {
        process.stdout.write("UNKNOWN");
      }
    });
  '
}

wait_for_deployment() {
  local service="$1" status="UNKNOWN" attempts=0
  while (( attempts < 60 )); do
    status=$(railway deployment list --service "$service" --limit 1 --json |
      latest_deployment_status)
    case "$status" in
      SUCCESS)
        printf '  %s✓ deployed%s %s\n' "$GREEN" "$RESET" "$service"
        return 0
        ;;
      FAILED|CRASHED|NEEDS_APPROVAL|SLEEPING|SKIPPED|REMOVED|REMOVING)
        warn "$service deployment reached $status"
        railway logs --service "$service" --lines 100 || true
        return 1
        ;;
      *)
        printf '  %s…%s %s: %s\r' "$DIM" "$RESET" "$service" "$status"
        sleep 10
        ;;
    esac
    attempts=$((attempts + 1))
  done
  printf '\n'
  warn "timed out waiting for $service; inspect it with railway deployment list"
  return 1
}

banner "v7-chat Railway setup"

stage "Railway account and project" 3
require_command railway
require_command node
require_command git
if ! railway whoami >/dev/null 2>&1; then
  say "Railway will open its unified sign-in/sign-up flow in your browser."
  railway login
fi
if ! railway status >/dev/null 2>&1; then
  say "This checkout is not linked to a Railway project."
  if confirm "Create and link a new project named v7-chat?"; then
    railway init --name v7-chat
  else
    step "Choose the existing Railway project and environment."
    railway link
  fi
fi
say "Railway context:"
railway status

stage "Clerk credentials" 3
say "Use a Clerk instance intended for this Railway environment."
open_url "https://dashboard.clerk.com/last-active?path=api-keys"
step "Copy the publishable key and secret key from Clerk's API keys page."
CLERK_VALUES_CHANGED=true
if shared_variable_exists NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY &&
  shared_variable_exists CLERK_SECRET_KEY; then
  note "Clerk variables already exist. Leave both prompts blank to retain them."
fi
ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Publishable key:"
ask_secret CLERK_SECRET_KEY "Secret key:"
if [[ -z "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" && -z "$CLERK_SECRET_KEY" ]] &&
  shared_variable_exists NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY &&
  shared_variable_exists CLERK_SECRET_KEY; then
  CLERK_VALUES_CHANGED=false
elif [[ -z "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" || -z "$CLERK_SECRET_KEY" ]]; then
  warn "provide both Clerk keys, or leave both blank to retain existing keys"
  exit 1
fi

stage "Model provider" 2
say "Choose 'mock' for an offline demonstration or 'openrouter' for real models."
MODEL_VALUES_CHANGED=true
MODEL_DEFAULT=mock
if shared_variable_exists MODEL_PROVIDER && shared_variable_exists OPENROUTER_API_KEY; then
  MODEL_DEFAULT=keep
  note "Model variables already exist; Enter retains them."
fi
ask MODEL_PROVIDER "Model provider [keep/mock/openrouter] (default: $MODEL_DEFAULT):"
MODEL_PROVIDER=${MODEL_PROVIDER:-$MODEL_DEFAULT}
case "$MODEL_PROVIDER" in
  keep)
    MODEL_VALUES_CHANGED=false
    ;;
  mock)
    OPENROUTER_API_KEY=""
    ;;
  openrouter)
    open_url "https://openrouter.ai/settings/keys"
    ask_secret OPENROUTER_API_KEY "OpenRouter API key:"
    [[ -n "$OPENROUTER_API_KEY" ]] || { warn "OpenRouter key is required"; exit 1; }
    ;;
  *)
    warn "MODEL_PROVIDER must be keep, mock, or openrouter"
    exit 1
    ;;
esac

stage "Database credentials" 1
require_command openssl
APP_PASSWORD_EXISTS=false
ADMIN_PASSWORD_EXISTS=false
READONLY_PASSWORD_EXISTS=false
shared_variable_exists APP_DB_PASSWORD && APP_PASSWORD_EXISTS=true
shared_variable_exists INTERMEDIATE_ADMIN_PASSWORD && ADMIN_PASSWORD_EXISTS=true
shared_variable_exists INTERMEDIATE_READONLY_PASSWORD && READONLY_PASSWORD_EXISTS=true
DATABASE_PASSWORD_COUNT=0
[[ "$APP_PASSWORD_EXISTS" == true ]] && DATABASE_PASSWORD_COUNT=$((DATABASE_PASSWORD_COUNT + 1))
[[ "$ADMIN_PASSWORD_EXISTS" == true ]] && DATABASE_PASSWORD_COUNT=$((DATABASE_PASSWORD_COUNT + 1))
[[ "$READONLY_PASSWORD_EXISTS" == true ]] && DATABASE_PASSWORD_COUNT=$((DATABASE_PASSWORD_COUNT + 1))
if (( DATABASE_PASSWORD_COUNT == 3 )); then
  note "Existing sealed database credentials retained."
elif (( DATABASE_PASSWORD_COUNT > 0 )); then
  warn "only some database credentials exist; refusing an unsafe partial rotation"
  say "Restore the missing sealed variables or follow the rotation procedure in docs/configuration.md."
  exit 1
else
  say "Generating URL-safe credentials for both private databases."
  APP_DB_PASSWORD=$(openssl rand -hex 32)
  INTERMEDIATE_ADMIN_PASSWORD=$(openssl rand -hex 32)
  INTERMEDIATE_READONLY_PASSWORD=$(openssl rand -hex 32)
  DATABASE_VALUES_CHANGED=true
fi
DATABASE_VALUES_CHANGED=${DATABASE_VALUES_CHANGED:-false}

stage "Infrastructure plan and deployment" 5
if [[ "$(git branch --show-current)" != "main" ]]; then
  warn "Railway sources are pinned to main; switch to main before applying"
  exit 1
fi
if ! git diff --quiet || ! git diff --cached --quiet; then
  warn "the checkout has uncommitted tracked changes"
  say "Commit the Railway deployment files before applying so Railway can build them."
  exit 1
fi
for required_file in \
  .railway/railway.ts \
  deploy/railway/intermediate-db/Dockerfile \
  deploy/railway/intermediate-db/init-intermediate.sh; do
  if ! git ls-files --error-unmatch "$required_file" >/dev/null 2>&1; then
    warn "$required_file is not committed"
    say "Commit the Railway deployment files before applying."
    exit 1
  fi
done
git fetch origin main
LOCAL_HEAD=$(git rev-parse HEAD)
REMOTE_HEAD=$(git rev-parse origin/main 2>/dev/null || true)
if [[ "$LOCAL_HEAD" != "$REMOTE_HEAD" ]]; then
  warn "origin/main does not yet contain this local main commit"
  if confirm "Push local main to origin/main now?"; then
    git push origin main
  else
    say "Push main, then rerun this wizard. The stored Railway variables are safe."
    exit 1
  fi
fi
railway config plan
if ! confirm "Store the captured variables and apply this Railway infrastructure plan?"; then
  say "The infrastructure plan and captured variables were not applied."
  note "Only the Railway account/project link from stage 1 may have changed."
  exit 0
fi
if [[ "$CLERK_VALUES_CHANGED" == true ]]; then
  set_shared_variable NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" false
  set_shared_variable CLERK_SECRET_KEY "$CLERK_SECRET_KEY" true
fi
unset CLERK_SECRET_KEY NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
if [[ "$MODEL_VALUES_CHANGED" == true ]]; then
  set_shared_variable MODEL_PROVIDER "$MODEL_PROVIDER" false
  set_shared_variable OPENROUTER_API_KEY "$OPENROUTER_API_KEY" true
fi
unset OPENROUTER_API_KEY MODEL_PROVIDER
if [[ "$DATABASE_VALUES_CHANGED" == true ]]; then
  set_shared_variable APP_DB_PASSWORD "$APP_DB_PASSWORD" true
  set_shared_variable INTERMEDIATE_ADMIN_PASSWORD "$INTERMEDIATE_ADMIN_PASSWORD" true
  set_shared_variable INTERMEDIATE_READONLY_PASSWORD "$INTERMEDIATE_READONLY_PASSWORD" true
fi
unset APP_DB_PASSWORD INTERMEDIATE_ADMIN_PASSWORD INTERMEDIATE_READONLY_PASSWORD
if ! shared_variable_exists OPENROUTER_APP_URL; then
  set_shared_variable OPENROUTER_APP_URL "http://localhost:3000" false
fi
railway config apply
wait_for_deployment app-db
wait_for_deployment intermediate-db
wait_for_deployment app

stage "Public domain and Clerk authorization" 3
DOMAIN_JSON=$(railway domain list --service app --json 2>/dev/null || true)
RAILWAY_DOMAIN=$(printf '%s' "$DOMAIN_JSON" | json_railway_domain)
if [[ -z "$RAILWAY_DOMAIN" ]]; then
  DOMAIN_JSON=$(railway domain --service app --json)
  RAILWAY_DOMAIN=$(printf '%s' "$DOMAIN_JSON" | json_railway_domain)
fi
[[ -n "$RAILWAY_DOMAIN" ]] || { warn "could not determine the Railway domain"; exit 1; }
printf '  %s✓ domain%s https://%s\n' "$GREEN" "$RESET" "$RAILWAY_DOMAIN"
set_shared_variable OPENROUTER_APP_URL "https://$RAILWAY_DOMAIN" false
sleep 5
wait_for_deployment app
open_url "https://dashboard.clerk.com/last-active"
step "In the selected Clerk application, authorize this origin and its sign-in/sign-up redirects:"
say "https://$RAILWAY_DOMAIN"
pause "Press Enter after Clerk accepts the Railway domain."

stage "Business-data import" 2
for table in cities malls stores; do
  if [[ ! -f "data/$table.csv" ]]; then
    warn "data/$table.csv is missing"
    step "Copy cities.csv, malls.csv, and stores.csv into data/."
    pause "Press Enter after the CSV files are present."
    break
  fi
done
for table in cities malls stores; do
  [[ -f "data/$table.csv" ]] || { warn "data/$table.csv is still missing"; exit 1; }
done
./scripts/import-intermediate-csv.sh --railway

stage "Verification" 1
railway ssh --service intermediate-db -- sh -lc \
  'psql "$READONLY_DATABASE_URL" -v ON_ERROR_STOP=1 -c "show default_transaction_read_only" -c "select count(*) as cities from aiqa.cities"'
HEALTH=$(curl -fsS "https://$RAILWAY_DOMAIN/api/health")
printf '  %s✓ health%s %s\n' "$GREEN" "$RESET" "$HEALTH"

finish
say "Railway deployment: https://$RAILWAY_DOMAIN"
note "Future pushes to main deploy the app and analytical image automatically."
